### ISSUE TITLE
Bug Fix: Images can have no copyright

### ISSUE THREAD

**Issue by fortmea** [fortmea/CosmicBeacon#4]
Null check operator used on a null value

The relevant error-causing widget was:
  ImageFragment
  ImageFragment:file:///C:/Users/joaow/Documents/GitHub/CosmicBeacon/cosmic_beacon/lib/screens/home.dart:29:13

When the exception was thrown, this was the stack:
#0      ImageFragment.build.<anonymous closure> (package:cosmic_beacon/fragments/image_fragment.dart:246:54)
#1      AsyncValueX.when (package:riverpod/src/common.dart:741:16)
#2      ImageFragment.build (package:cosmic_beacon/fragments/image_fragment.dart:39:21)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:19)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#15     _invoke (dart:ui/hooks.dart:312:13)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#17     _drawFrame (dart:ui/hooks.dart:283:31)

**Comment by fortmea** [comment]
Fix is being deployed to production
